# Generated by Django 5.1.5 on 2025-01-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='high_priority',
            field=models.BooleanField(default=False),
        ),
    ]
