# Generated by Django 5.1.5 on 2025-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_high_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='high_priority',
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(default='low', max_length=10),
        ),
    ]
