# Generated by Django 5.1.5 on 2025-01-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_high_priority_note_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.CharField(default='low', max_length=20),
        ),
    ]
